using Spectra.Core.Index;
using Spectra.Core.Models.Index;

namespace Spectra.Core.Tests.Index;

public class DocIndexManifestRoundTripTests
{
    [Fact]
    public void Render_WriteThenRead_PreservesAllFields()
    {
        var original = new DocIndexManifest
        {
            Version = 2,
            GeneratedAt = new DateTimeOffset(2026, 4, 29, 15, 0, 0, TimeSpan.Zero),
            TotalDocuments = 2,
            TotalWords = 1000,
            TotalTokensEstimated = 1300,
            Groups = new List<DocSuiteEntry>
            {
                new()
                {
                    Id = "checkout",
                    Title = "Checkout",
                    Path = "docs/checkout",
                    DocumentCount = 1,
                    TokensEstimated = 800,
                    SkipAnalysis = false,
                    ExcludedBy = "none",
                    IndexFile = "groups/checkout.index.md",
                },
                new()
                {
                    Id = "payments",
                    Title = "Payments",
                    Path = "docs/payments",
                    DocumentCount = 1,
                    TokensEstimated = 500,
                    SkipAnalysis = false,
                    ExcludedBy = "none",
                    IndexFile = "groups/payments.index.md",
                },
            },
        };

        var yaml = DocIndexManifestWriter.Render(original);
        var roundtrip = DocIndexManifestReader.Parse(yaml);

        Assert.Equal(original.Version, roundtrip.Version);
        Assert.Equal(original.TotalDocuments, roundtrip.TotalDocuments);
        Assert.Equal(original.TotalWords, roundtrip.TotalWords);
        Assert.Equal(original.TotalTokensEstimated, roundtrip.TotalTokensEstimated);
        Assert.Equal(2, roundtrip.Groups.Count);
        Assert.Equal("checkout", roundtrip.Groups[0].Id);
        Assert.Equal("payments", roundtrip.Groups[1].Id);
    }

    [Fact]
    public void Render_PrependsAutoGeneratedComment()
    {
        var manifest = MinimalManifest();

        var yaml = DocIndexManifestWriter.Render(manifest);

        Assert.StartsWith("# Auto-generated by `spectra docs index`. Do not edit by hand.", yaml);
    }

    [Fact]
    public void Render_OmitsExcludedPattern_WhenNotPatternMatched()
    {
        var manifest = MinimalManifest();

        var yaml = DocIndexManifestWriter.Render(manifest);

        Assert.DoesNotContain("excluded_pattern", yaml);
    }

    [Fact]
    public void Render_EmitsExcludedPattern_WhenPatternFlagged()
    {
        var manifest = new DocIndexManifest
        {
            Version = 2,
            GeneratedAt = DateTimeOffset.UtcNow,
            TotalDocuments = 1,
            TotalWords = 0,
            TotalTokensEstimated = 0,
            Groups = new List<DocSuiteEntry>
            {
                new()
                {
                    Id = "Old",
                    Title = "Old",
                    Path = "docs/Old",
                    DocumentCount = 1,
                    TokensEstimated = 0,
                    SkipAnalysis = true,
                    ExcludedBy = "pattern",
                    ExcludedPattern = "**/Old/**",
                    IndexFile = "groups/Old.index.md",
                },
            },
        };

        var yaml = DocIndexManifestWriter.Render(manifest);
        var parsed = DocIndexManifestReader.Parse(yaml);

        Assert.Contains("excluded_pattern", yaml);
        Assert.Equal("**/Old/**", parsed.Groups[0].ExcludedPattern);
    }

    [Fact]
    public void Parse_RejectsUnsupportedVersion()
    {
        var yaml = "version: 1\ngenerated_at: 2026-04-29T00:00:00Z\ntotal_documents: 0\ntotal_words: 0\ntotal_tokens_estimated: 0\ngroups: []\n";

        var ex = Assert.Throws<InvalidOperationException>(() => DocIndexManifestReader.Parse(yaml));
        Assert.Contains("version", ex.Message, StringComparison.OrdinalIgnoreCase);
    }

    [Fact]
    public void Render_RejectsDuplicateSuiteId()
    {
        var manifest = new DocIndexManifest
        {
            Version = 2,
            GeneratedAt = DateTimeOffset.UtcNow,
            TotalDocuments = 0,
            TotalWords = 0,
            TotalTokensEstimated = 0,
            Groups = new List<DocSuiteEntry>
            {
                new() { Id = "dup", Path = "docs/x", IndexFile = "groups/dup.index.md", ExcludedBy = "none" },
                new() { Id = "dup", Path = "docs/y", IndexFile = "groups/dup.index.md", ExcludedBy = "none" },
            },
        };

        Assert.Throws<InvalidOperationException>(() => DocIndexManifestWriter.Render(manifest));
    }

    [Fact]
    public void Render_IsDeterministic_WhenCalledTwice()
    {
        var manifest = MinimalManifest();

        var yaml1 = DocIndexManifestWriter.Render(manifest);
        var yaml2 = DocIndexManifestWriter.Render(manifest);

        Assert.Equal(yaml1, yaml2);
    }

    [Fact]
    public void Render_SortsGroupsByIdOrdinal()
    {
        var manifest = new DocIndexManifest
        {
            Version = 2,
            GeneratedAt = DateTimeOffset.UtcNow,
            TotalDocuments = 0,
            TotalWords = 0,
            TotalTokensEstimated = 0,
            Groups = new List<DocSuiteEntry>
            {
                new() { Id = "zeta", Path = "docs/z", IndexFile = "groups/zeta.index.md", ExcludedBy = "none" },
                new() { Id = "alpha", Path = "docs/a", IndexFile = "groups/alpha.index.md", ExcludedBy = "none" },
                new() { Id = "mu", Path = "docs/m", IndexFile = "groups/mu.index.md", ExcludedBy = "none" },
            },
        };

        var yaml = DocIndexManifestWriter.Render(manifest);
        var alphaIdx = yaml.IndexOf("alpha", StringComparison.Ordinal);
        var muIdx = yaml.IndexOf("mu", StringComparison.Ordinal);
        var zetaIdx = yaml.IndexOf("zeta", StringComparison.Ordinal);

        Assert.True(alphaIdx > 0);
        Assert.True(alphaIdx < muIdx);
        Assert.True(muIdx < zetaIdx);
    }

    private static DocIndexManifest MinimalManifest() => new()
    {
        Version = 2,
        GeneratedAt = new DateTimeOffset(2026, 4, 29, 15, 0, 0, TimeSpan.Zero),
        TotalDocuments = 0,
        TotalWords = 0,
        TotalTokensEstimated = 0,
        Groups = new List<DocSuiteEntry>(),
    };
}
