using Spectra.Core.Index;
using Spectra.Core.Models;

namespace Spectra.Core.Tests.Index;

public class DocumentIndexWriterTests
{
    [Fact]
    public void Render_ContainsHeader()
    {
        var index = CreateSampleIndex();
        var markdown = DocumentIndexWriter.Render(index);

        Assert.Contains("# Documentation Index", markdown);
        Assert.Contains("Auto-generated by Spectra", markdown);
    }

    [Fact]
    public void Render_ContainsTotals()
    {
        var index = CreateSampleIndex();
        var markdown = DocumentIndexWriter.Render(index);

        Assert.Contains("1 documents", markdown);
        Assert.Contains("100 words", markdown);
        Assert.Contains("~130 tokens", markdown);
    }

    [Fact]
    public void Render_ContainsEntryPath()
    {
        var index = CreateSampleIndex();
        var markdown = DocumentIndexWriter.Render(index);

        Assert.Contains("### docs/test.md", markdown);
    }

    [Fact]
    public void Render_ContainsEntryMetadata()
    {
        var index = CreateSampleIndex();
        var markdown = DocumentIndexWriter.Render(index);

        Assert.Contains("**Title:** Test Document", markdown);
        Assert.Contains("**Size:** 5 KB", markdown);
        Assert.Contains("**Words:** 100", markdown);
        Assert.Contains("**Tokens:** ~130", markdown);
    }

    [Fact]
    public void Render_ContainsSectionsTable()
    {
        var index = CreateSampleIndex();
        var markdown = DocumentIndexWriter.Render(index);

        Assert.Contains("| Section | Summary |", markdown);
        Assert.Contains("Overview", markdown);
        Assert.Contains("This is the overview", markdown);
    }

    [Fact]
    public void Render_ContainsKeyEntities()
    {
        var index = CreateSampleIndex();
        var markdown = DocumentIndexWriter.Render(index);

        Assert.Contains("**Key Entities:** Entity1, Entity2", markdown);
    }

    [Fact]
    public void Render_ContainsChecksumComment()
    {
        var index = CreateSampleIndex();
        var markdown = DocumentIndexWriter.Render(index);

        Assert.Contains("SPECTRA_INDEX_CHECKSUMS", markdown);
        Assert.Contains("abc123", markdown);
    }

    [Fact]
    public void Render_H3SectionsShowArrowPrefix()
    {
        var index = new DocumentIndex
        {
            GeneratedAt = DateTimeOffset.UtcNow,
            TotalWordCount = 100,
            TotalEstimatedTokens = 130,
            Entries =
            [
                new DocumentIndexEntry
                {
                    Path = "docs/test.md",
                    Title = "Test",
                    Sections =
                    [
                        new SectionSummary { Heading = "Parent", Level = 2, Summary = "Parent section" },
                        new SectionSummary { Heading = "Child", Level = 3, Summary = "Child section" }
                    ],
                    KeyEntities = [],
                    WordCount = 100,
                    EstimatedTokens = 130,
                    SizeKb = 1,
                    LastModified = DateTimeOffset.UtcNow,
                    ContentHash = "abc"
                }
            ]
        };

        var markdown = DocumentIndexWriter.Render(index);

        Assert.Contains("↳ Child", markdown);
    }

    [Fact]
    public async Task WriteAsync_CreatesFile()
    {
        var index = CreateSampleIndex();
        var path = Path.Combine(Path.GetTempPath(), Guid.NewGuid().ToString(), "_index.md");

        var writer = new DocumentIndexWriter();
        await writer.WriteAsync(path, index);

        Assert.True(File.Exists(path));
        var content = await File.ReadAllTextAsync(path);
        Assert.Contains("# Documentation Index", content);

        // Cleanup
        File.Delete(path);
        Directory.Delete(Path.GetDirectoryName(path)!);
    }

    [Fact]
    public void Render_RoundTripsWithReader()
    {
        var index = CreateSampleIndex();
        var markdown = DocumentIndexWriter.Render(index);
        var parsed = DocumentIndexReader.ParseFull(markdown);

        Assert.NotNull(parsed);
        Assert.Equal(1, parsed.TotalDocuments);
        Assert.Equal("docs/test.md", parsed.Entries[0].Path);
        Assert.Equal("Test Document", parsed.Entries[0].Title);
        Assert.Equal(100, parsed.Entries[0].WordCount);
        Assert.Equal("abc123", parsed.Entries[0].ContentHash);
    }

    private static DocumentIndex CreateSampleIndex() => new()
    {
        GeneratedAt = DateTimeOffset.UtcNow,
        TotalWordCount = 100,
        TotalEstimatedTokens = 130,
        Entries =
        [
            new DocumentIndexEntry
            {
                Path = "docs/test.md",
                Title = "Test Document",
                Sections =
                [
                    new SectionSummary { Heading = "Overview", Level = 2, Summary = "This is the overview" }
                ],
                KeyEntities = ["Entity1", "Entity2"],
                WordCount = 100,
                EstimatedTokens = 130,
                SizeKb = 5,
                LastModified = new DateTimeOffset(2026, 3, 18, 0, 0, 0, TimeSpan.Zero),
                ContentHash = "abc123"
            }
        ]
    };
}
