using Spectra.Core.Index;
using Spectra.Core.Models;

namespace Spectra.Core.Tests.Index;

public class DocumentIndexReaderTests
{
    private const string SampleIndexContent = """
        # Documentation Index

        > Auto-generated by Spectra. Last updated: 2026-03-20T14:30:00Z
        > Total: 2 documents | 200 words | ~260 tokens

        ---

        ### docs/registration.md
        - **Title:** Citizen Registration
        - **Size:** 10 KB | **Words:** 150 | **Tokens:** ~195
        - **Last Modified:** 2026-03-18
        - **Key Entities:** QES, EGN, Registration Wizard

        | Section | Summary |
        |---------|---------|
        | Registration Wizard | The citizen registration process follows a wizard... |
        |   ↳ Step 1 | Citizens must provide personal information... |

        ---

        ### docs/payments.md
        - **Title:** Payment Processing
        - **Size:** 8 KB | **Words:** 50 | **Tokens:** ~65
        - **Last Modified:** 2026-03-19

        ---

        <!-- SPECTRA_INDEX_CHECKSUMS
        {"docs/registration.md":"aabbccdd","docs/payments.md":"eeff0011"}
        -->
        """;

    [Fact]
    public void ExtractChecksums_ParsesCorrectly()
    {
        var checksums = DocumentIndexReader.ExtractChecksums(SampleIndexContent);

        Assert.NotNull(checksums);
        Assert.Equal(2, checksums.Count);
        Assert.Equal("aabbccdd", checksums["docs/registration.md"]);
        Assert.Equal("eeff0011", checksums["docs/payments.md"]);
    }

    [Fact]
    public void ExtractChecksums_ReturnsNullForMalformedInput()
    {
        var result = DocumentIndexReader.ExtractChecksums("no checksums here");
        Assert.Null(result);
    }

    [Fact]
    public void ParseFull_ParsesAllEntries()
    {
        var index = DocumentIndexReader.ParseFull(SampleIndexContent);

        Assert.NotNull(index);
        Assert.Equal(2, index.TotalDocuments);
    }

    [Fact]
    public void ParseFull_ParsesGeneratedAt()
    {
        var index = DocumentIndexReader.ParseFull(SampleIndexContent);

        Assert.NotNull(index);
        Assert.Equal(new DateTimeOffset(2026, 3, 20, 14, 30, 0, TimeSpan.Zero), index.GeneratedAt);
    }

    [Fact]
    public void ParseFull_ParsesEntryMetadata()
    {
        var index = DocumentIndexReader.ParseFull(SampleIndexContent);
        Assert.NotNull(index);

        var registration = index.Entries.First(e => e.Path == "docs/registration.md");
        Assert.Equal("Citizen Registration", registration.Title);
        Assert.Equal(10, registration.SizeKb);
        Assert.Equal(150, registration.WordCount);
        Assert.Equal(195, registration.EstimatedTokens);
        Assert.Equal("aabbccdd", registration.ContentHash);
    }

    [Fact]
    public void ParseFull_ParsesKeyEntities()
    {
        var index = DocumentIndexReader.ParseFull(SampleIndexContent);
        Assert.NotNull(index);

        var registration = index.Entries.First(e => e.Path == "docs/registration.md");
        Assert.Contains("QES", registration.KeyEntities);
        Assert.Contains("EGN", registration.KeyEntities);
        Assert.Contains("Registration Wizard", registration.KeyEntities);
    }

    [Fact]
    public void ParseFull_ParsesSectionsTable()
    {
        var index = DocumentIndexReader.ParseFull(SampleIndexContent);
        Assert.NotNull(index);

        var registration = index.Entries.First(e => e.Path == "docs/registration.md");
        Assert.Equal(2, registration.Sections.Count);
        Assert.Equal("Registration Wizard", registration.Sections[0].Heading);
        Assert.Equal(2, registration.Sections[0].Level);
        Assert.Equal("Step 1", registration.Sections[1].Heading);
        Assert.Equal(3, registration.Sections[1].Level);
    }

    [Fact]
    public void ParseFull_HandlesEntryWithoutSections()
    {
        var index = DocumentIndexReader.ParseFull(SampleIndexContent);
        Assert.NotNull(index);

        var payments = index.Entries.First(e => e.Path == "docs/payments.md");
        Assert.Empty(payments.Sections);
    }

    [Fact]
    public async Task ReadHashesOnlyAsync_ReturnsNullForMissingFile()
    {
        var reader = new DocumentIndexReader();
        var result = await reader.ReadHashesOnlyAsync("/nonexistent/path/_index.md");
        Assert.Null(result);
    }

    [Fact]
    public async Task ReadFullAsync_ReturnsNullForMissingFile()
    {
        var reader = new DocumentIndexReader();
        var result = await reader.ReadFullAsync("/nonexistent/path/_index.md");
        Assert.Null(result);
    }

    [Fact]
    public async Task ReadHashesOnlyAsync_ReadFromFile()
    {
        var path = Path.GetTempFileName();
        await File.WriteAllTextAsync(path, SampleIndexContent);

        var reader = new DocumentIndexReader();
        var hashes = await reader.ReadHashesOnlyAsync(path);

        Assert.NotNull(hashes);
        Assert.Equal(2, hashes.Count);

        File.Delete(path);
    }

    [Fact]
    public void ParseFull_ComputesTotalsFromEntries()
    {
        var index = DocumentIndexReader.ParseFull(SampleIndexContent);
        Assert.NotNull(index);

        Assert.Equal(200, index.TotalWordCount);
        Assert.Equal(260, index.TotalEstimatedTokens);
    }
}
