using Spectra.Core.Models.Coverage;
using YamlDotNet.Serialization;
using YamlDotNet.Serialization.NamingConventions;

namespace Spectra.Core.Parsing;

/// <summary>
/// Writes _criteria_index.yaml master index files with atomic write.
/// </summary>
public sealed class CriteriaIndexWriter
{
    private static readonly ISerializer Serializer = new SerializerBuilder()
        .WithNamingConvention(UnderscoredNamingConvention.Instance)
        .ConfigureDefaultValuesHandling(DefaultValuesHandling.OmitNull)
        .Build();

    /// <summary>
    /// Writes the criteria index to a YAML file atomically (temp file + rename).
    /// </summary>
    public async Task WriteAsync(string filePath, CriteriaIndex index, CancellationToken ct = default)
    {
        var dir = Path.GetDirectoryName(filePath);
        if (!string.IsNullOrEmpty(dir))
            Directory.CreateDirectory(dir);

        // Recalculate total
        index.TotalCriteria = index.Sources.Sum(s => s.CriteriaCount);

        var header = $"# Auto-generated by SPECTRA. Do not edit manually.{Environment.NewLine}" +
                     $"# Last updated: {DateTime.UtcNow:o}{Environment.NewLine}";
        var yaml = Serializer.Serialize(index);

        var tempPath = filePath + ".tmp";
        await File.WriteAllTextAsync(tempPath, header + yaml, ct);
        File.Move(tempPath, filePath, overwrite: true);
    }
}
