using System.CommandLine;
using System.Text.Json;
using Spectra.CLI.Commands.Docs;
using Spectra.CLI.Options;
using Spectra.Core.Index;
using Spectra.Core.Models.Config;

namespace Spectra.CLI.Tests.Commands.Docs;

/// <summary>
/// End-to-end tests for the v2 layout produced by <see cref="DocsIndexHandler"/>.
/// Drives the handler through <c>RootCommand.InvokeAsync</c> for realistic
/// flag wiring; covers the migration trigger, fresh-project path, and the
/// `--no-migrate` / `--suites` flags.
/// </summary>
[Collection("WorkingDirectory")]
public class DocsIndexHandler_NewLayoutTests : IDisposable
{
    private readonly string _testDir;

    public DocsIndexHandler_NewLayoutTests()
    {
        _testDir = Path.Combine(Path.GetTempPath(), $"spectra-newlayout-test-{Guid.NewGuid():N}");
        Directory.CreateDirectory(_testDir);
    }

    public void Dispose()
    {
        try
        {
            if (Directory.Exists(_testDir))
            {
                GC.Collect();
                GC.WaitForPendingFinalizers();
                Directory.Delete(_testDir, recursive: true);
            }
        }
        catch (IOException) { }
    }

    private async Task SeedConfigAsync()
    {
        var config = SpectraConfig.Default;
        await File.WriteAllTextAsync(
            Path.Combine(_testDir, "spectra.config.json"),
            JsonSerializer.Serialize(config, new JsonSerializerOptions { WriteIndented = true }));
    }

    private async Task SeedDocAsync(string relativePath, string content)
    {
        var fullPath = Path.Combine(_testDir, relativePath.Replace('/', Path.DirectorySeparatorChar));
        Directory.CreateDirectory(Path.GetDirectoryName(fullPath)!);
        await File.WriteAllTextAsync(fullPath, content);
    }

    private async Task<int> RunDocsIndexAsync(params string[] extraArgs)
    {
        var originalDir = Directory.GetCurrentDirectory();
        try
        {
            Directory.SetCurrentDirectory(_testDir);

            var command = new RootCommand();
            GlobalOptions.AddTo(command);
            command.AddCommand(new DocsCommand());
            var args = new List<string> { "docs", "index" };
            args.AddRange(extraArgs);
            return await command.InvokeAsync(args.ToArray());
        }
        finally
        {
            Directory.SetCurrentDirectory(originalDir);
        }
    }

    [Fact]
    public async Task ExecuteAsync_FreshProject_WritesAllThreeArtifacts()
    {
        await SeedConfigAsync();
        await SeedDocAsync("docs/checkout.md", "# Checkout\n\n## Overview\n\nCheckout flow.");
        await SeedDocAsync("docs/payments.md", "# Payments\n\n## Overview\n\nPayments flow.");

        var exitCode = await RunDocsIndexAsync("--skip-criteria");

        Assert.Equal(0, exitCode);
        var indexDir = Path.Combine(_testDir, "docs", "_index");
        Assert.True(File.Exists(Path.Combine(indexDir, "_manifest.yaml")));
        Assert.True(File.Exists(Path.Combine(indexDir, "_checksums.json")));
        Assert.True(Directory.Exists(Path.Combine(indexDir, "groups")));
    }

    [Fact]
    public async Task ExecuteAsync_FreshProject_ManifestReflectsDocs()
    {
        await SeedConfigAsync();
        await SeedDocAsync("docs/checkout.md", "# Checkout\n\nCheckout flow content.");

        await RunDocsIndexAsync("--skip-criteria");

        var manifestPath = Path.Combine(_testDir, "docs", "_index", "_manifest.yaml");
        var manifest = await new DocIndexManifestReader().ReadAsync(manifestPath);
        Assert.NotNull(manifest);
        Assert.Equal(2, manifest!.Version);
        Assert.Equal(1, manifest.TotalDocuments);
        Assert.NotEmpty(manifest.Groups);
    }

    [Fact]
    public async Task ExecuteAsync_LegacyFilePresent_TriggersMigration()
    {
        await SeedConfigAsync();
        // Simulate an existing legacy single-file index in lieu of an indexed docs/.
        var legacyPath = Path.Combine(_testDir, "docs", "_index.md");
        Directory.CreateDirectory(Path.GetDirectoryName(legacyPath)!);
        await File.WriteAllTextAsync(legacyPath, """
        # Documentation Index

        > Auto-generated by Spectra. Last updated: 2026-04-29T15:00:00Z
        > Total: 1 documents | 100 words | ~130 tokens

        ---

        ### docs/checkout.md
        - **Title:** Checkout
        - **Size:** 1 KB | **Words:** 100 | **Tokens:** ~130
        - **Last Modified:** 2026-04-15

        | Section | Summary |
        |---------|---------|
        | Overview | Checkout flow. |

        ---

        <!-- SPECTRA_INDEX_CHECKSUMS
        {"docs/checkout.md":"abc123def456abc123def456abc123def456abc123def456abc123def456abc1"}
        -->
        """);
        // Also seed an actual doc so re-indexing has something to walk.
        await SeedDocAsync("docs/checkout.md", "# Checkout\n\nCheckout flow.");

        var exitCode = await RunDocsIndexAsync("--skip-criteria");

        Assert.Equal(0, exitCode);
        // Migration produces _index.md.bak (the original) and the v2 layout.
        // Phase 4 (T049) removed the transition shim, so the legacy _index.md
        // is no longer rewritten — only the .bak survives.
        Assert.True(File.Exists(Path.Combine(_testDir, "docs", "_index.md.bak")));
        Assert.False(File.Exists(legacyPath));
        Assert.True(File.Exists(Path.Combine(_testDir, "docs", "_index", "_manifest.yaml")));
    }

    [Fact]
    public async Task ExecuteAsync_NoMigrateFlag_LegacyPresent_ReturnsError()
    {
        await SeedConfigAsync();
        var legacyPath = Path.Combine(_testDir, "docs", "_index.md");
        Directory.CreateDirectory(Path.GetDirectoryName(legacyPath)!);
        await File.WriteAllTextAsync(legacyPath, "# Documentation Index\n");
        await SeedDocAsync("docs/x.md", "# X\n");

        var exitCode = await RunDocsIndexAsync("--no-migrate");

        Assert.Equal(1, exitCode);
        // Legacy file untouched (no .bak created); v2 layout not written.
        Assert.True(File.Exists(legacyPath));
        Assert.False(File.Exists(legacyPath + ".bak"));
        Assert.False(File.Exists(Path.Combine(_testDir, "docs", "_index", "_manifest.yaml")));
    }

    [Fact]
    public async Task ExecuteAsync_AfterMigration_NextRunIsIncrementalNotMigration()
    {
        await SeedConfigAsync();
        await SeedDocAsync("docs/checkout.md", "# Checkout\n\nFirst version.");

        // First run: fresh project (no legacy file, no migration).
        var first = await RunDocsIndexAsync("--skip-criteria");
        Assert.Equal(0, first);

        var manifestPath = Path.Combine(_testDir, "docs", "_index", "_manifest.yaml");
        var firstMtime = File.GetLastWriteTimeUtc(manifestPath);

        // Wait a tick so the manifest's mtime would change if rewritten.
        await Task.Delay(50);

        // Second run: incremental, no migration. Manifest may be rewritten with
        // a fresh `generated_at` even if no docs changed; the key assertion is
        // that no .bak file is suddenly produced and the run still succeeds.
        var second = await RunDocsIndexAsync("--skip-criteria");
        Assert.Equal(0, second);
        Assert.False(File.Exists(Path.Combine(_testDir, "docs", "_index.md.bak")));
    }

    [Fact]
    public async Task ExecuteAsync_DryRun_DoesNotWriteV2Layout()
    {
        await SeedConfigAsync();
        await SeedDocAsync("docs/x.md", "# X\n");

        var exitCode = await RunDocsIndexAsync("--dry-run");

        Assert.Equal(0, exitCode);
        Assert.False(File.Exists(Path.Combine(_testDir, "docs", "_index", "_manifest.yaml")));
    }

    [Fact]
    public async Task ExecuteAsync_AppliesDefaultExclusionPatterns()
    {
        await SeedConfigAsync();
        await SeedDocAsync("docs/active/foo.md", "# Active\n\nContent.");
        await SeedDocAsync("docs/Old/x.md", "# Old\n\nLegacy content.");
        await SeedDocAsync("docs/archive/y.md", "# Archive\n\nArchived content.");

        var exitCode = await RunDocsIndexAsync("--skip-criteria");

        Assert.Equal(0, exitCode);
        var manifestPath = Path.Combine(_testDir, "docs", "_index", "_manifest.yaml");
        var manifest = await new DocIndexManifestReader().ReadAsync(manifestPath);
        Assert.NotNull(manifest);

        // The "active" suite should NOT be skipped.
        var active = manifest!.Groups.FirstOrDefault(g => g.Id == "active");
        Assert.NotNull(active);
        Assert.False(active!.SkipAnalysis);

        // "Old" and "archive" suites should be flagged via pattern.
        var oldSuite = manifest.Groups.FirstOrDefault(g => g.Id == "Old");
        Assert.NotNull(oldSuite);
        Assert.True(oldSuite!.SkipAnalysis);
        Assert.Equal("pattern", oldSuite.ExcludedBy);

        var archiveSuite = manifest.Groups.FirstOrDefault(g => g.Id == "archive");
        Assert.NotNull(archiveSuite);
        Assert.True(archiveSuite!.SkipAnalysis);
    }
}
