using System.Text;
using Spectra.Core.Models.Index;
using YamlDotNet.Serialization;
using YamlDotNet.Serialization.NamingConventions;

namespace Spectra.Core.Index;

/// <summary>
/// Writes <c>_manifest.yaml</c> (Spec 040 v2 layout) atomically.
/// </summary>
public sealed class DocIndexManifestWriter
{
    private const string LeadingComment =
        "# Auto-generated by `spectra docs index`. Do not edit by hand.\n";

    private static readonly ISerializer Serializer = new SerializerBuilder()
        .WithNamingConvention(UnderscoredNamingConvention.Instance)
        .ConfigureDefaultValuesHandling(DefaultValuesHandling.OmitNull)
        .DisableAliases()
        .Build();

    /// <summary>
    /// Writes <paramref name="manifest"/> to <paramref name="path"/>. Sorts groups
    /// by <see cref="DocSuiteEntry.Id"/> (ordinal) before emitting. Validates
    /// <c>total_documents == sum(group.document_count)</c> before writing —
    /// mismatch indicates a programming bug and throws.
    /// </summary>
    public async Task WriteAsync(string path, DocIndexManifest manifest, CancellationToken ct = default)
    {
        ArgumentException.ThrowIfNullOrWhiteSpace(path);
        ArgumentNullException.ThrowIfNull(manifest);

        var content = Render(manifest);
        await AtomicFileWriter.WriteAllTextAsync(path, content, ct);
    }

    /// <summary>
    /// Renders the manifest to a YAML string with the leading auto-generated comment.
    /// </summary>
    public static string Render(DocIndexManifest manifest)
    {
        ArgumentNullException.ThrowIfNull(manifest);

        ValidateInvariants(manifest);

        // Sort groups for deterministic output.
        manifest.Groups = manifest.Groups
            .OrderBy(g => g.Id, StringComparer.Ordinal)
            .ToList();

        var yaml = Serializer.Serialize(manifest);

        var sb = new StringBuilder();
        sb.Append(LeadingComment);
        sb.Append(yaml);
        return sb.ToString();
    }

    private static void ValidateInvariants(DocIndexManifest manifest)
    {
        if (manifest.Version != 2)
        {
            throw new InvalidOperationException(
                $"Manifest version must be 2 (got {manifest.Version}).");
        }

        var seen = new HashSet<string>(StringComparer.Ordinal);
        var sumDocs = 0;
        foreach (var group in manifest.Groups)
        {
            if (string.IsNullOrEmpty(group.Id))
            {
                throw new InvalidOperationException("Suite has empty Id.");
            }
            if (!DocSuiteEntry.IdRegex.IsMatch(group.Id))
            {
                throw new InvalidOperationException(
                    $"Suite ID '{group.Id}' does not match the allowed pattern.");
            }
            if (!seen.Add(group.Id))
            {
                throw new InvalidOperationException($"Duplicate suite ID: '{group.Id}'.");
            }
            if (string.IsNullOrEmpty(group.IndexFile)
                || !group.IndexFile.StartsWith("groups/", StringComparison.Ordinal)
                || !group.IndexFile.EndsWith(".index.md", StringComparison.Ordinal))
            {
                throw new InvalidOperationException(
                    $"Suite '{group.Id}' index_file must start with 'groups/' and end with '.index.md' (got '{group.IndexFile}').");
            }
            if (group.ExcludedBy == "pattern" && string.IsNullOrEmpty(group.ExcludedPattern))
            {
                throw new InvalidOperationException(
                    $"Suite '{group.Id}' has excluded_by=pattern but no excluded_pattern.");
            }
            if (group.ExcludedBy != "none" && !group.SkipAnalysis)
            {
                throw new InvalidOperationException(
                    $"Suite '{group.Id}' has excluded_by='{group.ExcludedBy}' but skip_analysis=false.");
            }
            sumDocs += group.DocumentCount;
        }

        if (sumDocs != manifest.TotalDocuments)
        {
            throw new InvalidOperationException(
                $"Manifest total_documents ({manifest.TotalDocuments}) does not match sum of group document_count ({sumDocs}).");
        }
    }
}
