using System.Text;
using System.Text.Json;
using Spectra.Core.Models;

namespace Spectra.Core.Index;

/// <summary>
/// Renders a DocumentIndex to Markdown format at docs/_index.md.
/// </summary>
public sealed class DocumentIndexWriter
{
    private static readonly JsonSerializerOptions JsonOptions = new()
    {
        WriteIndented = false
    };

    /// <summary>
    /// Writes the document index to a Markdown file.
    /// </summary>
    public async Task WriteAsync(string path, DocumentIndex index, CancellationToken ct = default)
    {
        ArgumentException.ThrowIfNullOrWhiteSpace(path);
        ArgumentNullException.ThrowIfNull(index);

        var directory = Path.GetDirectoryName(path);
        if (!string.IsNullOrEmpty(directory) && !Directory.Exists(directory))
        {
            Directory.CreateDirectory(directory);
        }

        var content = Render(index);
        await File.WriteAllTextAsync(path, content, ct);
    }

    /// <summary>
    /// Renders the document index to a Markdown string.
    /// </summary>
    public static string Render(DocumentIndex index)
    {
        var sb = new StringBuilder();

        sb.AppendLine("# Documentation Index");
        sb.AppendLine();
        sb.AppendLine($"> Auto-generated by Spectra. Last updated: {index.GeneratedAt:yyyy-MM-ddTHH:mm:ssZ}");
        sb.AppendLine($"> Total: {index.TotalDocuments} documents | {index.TotalWordCount:N0} words | ~{index.TotalEstimatedTokens:N0} tokens");
        sb.AppendLine();

        foreach (var entry in index.Entries)
        {
            sb.AppendLine("---");
            sb.AppendLine();
            sb.AppendLine($"### {entry.Path}");
            sb.AppendLine($"- **Title:** {entry.Title}");
            sb.AppendLine($"- **Size:** {entry.SizeKb} KB | **Words:** {entry.WordCount:N0} | **Tokens:** ~{entry.EstimatedTokens:N0}");
            sb.AppendLine($"- **Last Modified:** {entry.LastModified:yyyy-MM-dd}");

            if (entry.KeyEntities.Count > 0)
            {
                sb.AppendLine($"- **Key Entities:** {string.Join(", ", entry.KeyEntities)}");
            }

            sb.AppendLine();

            if (entry.Sections.Count > 0)
            {
                sb.AppendLine("| Section | Summary |");
                sb.AppendLine("|---------|---------|");
                foreach (var section in entry.Sections)
                {
                    var prefix = section.Level > 2 ? new string(' ', (section.Level - 2) * 2) + "↳ " : "";
                    var escapedSummary = section.Summary.Replace("|", "\\|").Replace("\n", " ");
                    sb.AppendLine($"| {prefix}{section.Heading} | {escapedSummary} |");
                }

                sb.AppendLine();
            }
        }

        // Append checksums as HTML comment
        var checksums = new Dictionary<string, string>();
        foreach (var entry in index.Entries)
        {
            checksums[entry.Path] = entry.ContentHash;
        }

        sb.AppendLine("---");
        sb.AppendLine();
        sb.AppendLine("<!-- SPECTRA_INDEX_CHECKSUMS");
        sb.AppendLine(JsonSerializer.Serialize(checksums, JsonOptions));
        sb.AppendLine("-->");

        return sb.ToString();
    }
}
